In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

import pickle

%matplotlib inline

In [2]:
with open('/Users/robertpagano/src/metis_project_mcnulty/data/interim_data/merged_data_cats_almost_ready.pickle', 'rb') as f:
    df = pickle.load(f)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.describe()

,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,outcome_year,outcome_month,outcome_day_of_week,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,is_kitten,is_cfa_breed,is_domestic_breed
count,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000,32054.000000
mean,0.444625,0.261340,2014.538622,6.136707,2015.810258,6.873183,2.940694,2015.845324,7.107974,3.088351,72.111443,71.576540,0.146215,0.141078,0.145380,0.129282,20.256442,487.149685,0.616148,0.054939,0.946372
std,0.496932,0.439372,3.034919,2.803705,1.495946,2.950752,2.002341,1.501786,3.081659,2.029236,12.668542,13.641624,0.481274,0.518947,0.352489,0.335517,38.041802,962.588621,0.486330,0.227864,0.225286
min,0.000000,0.000000,1992.000000,1.000000,2013.000000,1.000000,0.000000,2013.000000,1.000000,0.000000,25.700000,25.700000,0.000000,0.000000,0.000000,0.000000,0.000000,-50.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,2014.000000,4.000000,2015.000000,5.000000,1.000000,2015.000000,5.000000,1.000000,65.000000,62.900000,0.000000,0.000000,0.000000,0.000000,1.000000,31.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,2015.000000,6.000000,2016.000000,7.000000,3.000000,2016.000000,7.000000,3.000000,75.800000,75.900000,0.000000,0.000000,0.000000,0.000000,6.000000,76.000000,1.000000,0.000000,1.000000
75%,1.000000,1.000000,2016.000000,8.000000,2017.000000,9.000000,5.000000,2017.000000,10.000000,5.000000,81.800000,82.400000,0.030000,0.020000,0.000000,0.000000,26.000000,366.000000,1.000000,0.000000,1.000000
max,1.000000,1.000000,2019.000000,12.000000,2019.000000,12.000000,6.000000,2019.000000,12.000000,6.000000,92.300000,92.300000,7.000000,7.000000,1.000000,1.000000,1102.000000,8036.000000,1.000000,1.000000,1.000000

In [5]:
df.head()

,animal_id,date_intake,intake_type,intake_condition,sex_fixed_intake,age_raw,breed,color,date_outcome,dob,outcome_type,outcome_subtype,sex_fixed_outcome,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,intake_time_of_day,outcome_year,outcome_month,outcome_day_of_week,outcome_time_of_day,date_only_intake,date_only_outcome,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,cat_or_kitten,is_kitten,breed1,breed2,is_cfa_breed,is_domestic_breed,coat_pattern,color1,color2,coat
110062,A664235,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:39:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:39:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange
76631,A664237,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange
66872,A664236,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange
96315,A664238,2013-10-01 09:33:00,Stray,Normal,Unknown,4 months,american shorthair,black/white,2013-10-01 16:47:00,2013-06-01,Euthanasia,Medical,Unknown,0,1,2013,6,2013,10,1,09:33:00,2013,10,1,16:47:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,122,Kitten,1,american shorthair,None,1,0,NaN,black,white,black
117960,A664256,2013-10-01 10:59:00,Owner Surrender,Normal,Neutered Male,17 years,domestic shorthair,brown /white,2013-10-10 13:17:00,1996-10-01,Transfer,Partner,Neutered Male,1,1,1996,10,2013,10,1,10:59:00,2013,10,3,13:17:00,2013-10-01,2013-10-10,75.4,70.4,0.0,0.0,0,0,9,6209,Cat,0,domestic shorthair,None,0,1,tabby,brown,white,brown

In [6]:
df['outcome_type'].unique()

array(['Transfer', 'Euthanasia', 'Adoption', 'Died', 'Return to Owner',
       'Missing', 'Disposal', 'Rto-Adopt'], dtype=object)

Below I am filtering for just my target labels

In [7]:
df = df.loc[(df['outcome_type'] == 'Adoption') | (df['outcome_type'] == 'Transfer')]

In [8]:
df.head()

,animal_id,date_intake,intake_type,intake_condition,sex_fixed_intake,age_raw,breed,color,date_outcome,dob,outcome_type,outcome_subtype,sex_fixed_outcome,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,intake_time_of_day,outcome_year,outcome_month,outcome_day_of_week,outcome_time_of_day,date_only_intake,date_only_outcome,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,cat_or_kitten,is_kitten,breed1,breed2,is_cfa_breed,is_domestic_breed,coat_pattern,color1,color2,coat
110062,A664235,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:39:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:39:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange
76631,A664237,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange
66872,A664236,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange
117960,A664256,2013-10-01 10:59:00,Owner Surrender,Normal,Neutered Male,17 years,domestic shorthair,brown /white,2013-10-10 13:17:00,1996-10-01,Transfer,Partner,Neutered Male,1,1,1996,10,2013,10,1,10:59:00,2013,10,3,13:17:00,2013-10-01,2013-10-10,75.4,70.4,0.0,0.0,0,0,9,6209,Cat,0,domestic shorthair,None,0,1,tabby,brown,white,brown
113616,A664261,2013-10-01 11:21:00,Stray,Normal,Intact Female,3 weeks,domestic shorthair,,2013-10-01 13:00:00,2013-09-10,Transfer,Partner,Intact Female,0,0,2013,9,2013,10,1,11:21:00,2013,10,1,13:00:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,21,Kitten,1,domestic shorthair,None,0,1,tortie,Breed Specific,None,tortie

In [9]:
df['intake_type'].unique()

array(['Stray', 'Owner Surrender', 'Public Assist', 'Euthanasia Request'],
      dtype=object)

In [10]:
day_of_week={0:'Monday', 1:'Tuesday', 2:'Wednesday', 3:'Thursday', 4:'Friday', 5:'Saturday', 6:'Sunday'}
df['weekday_intake'] = df['intake_day_of_week'].map(day_of_week)
df['weekday_outcome'] = df['outcome_day_of_week'].map(day_of_week)

In [11]:
df.head()

,animal_id,date_intake,intake_type,intake_condition,sex_fixed_intake,age_raw,breed,color,date_outcome,dob,outcome_type,outcome_subtype,sex_fixed_outcome,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,intake_time_of_day,outcome_year,outcome_month,outcome_day_of_week,outcome_time_of_day,date_only_intake,date_only_outcome,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,cat_or_kitten,is_kitten,breed1,breed2,is_cfa_breed,is_domestic_breed,coat_pattern,color1,color2,coat,weekday_intake,weekday_outcome
110062,A664235,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:39:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:39:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange,Tuesday,Tuesday
76631,A664237,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange,Tuesday,Tuesday
66872,A664236,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange,Tuesday,Tuesday
117960,A664256,2013-10-01 10:59:00,Owner Surrender,Normal,Neutered Male,17 years,domestic shorthair,brown /white,2013-10-10 13:17:00,1996-10-01,Transfer,Partner,Neutered Male,1,1,1996,10,2013,10,1,10:59:00,2013,10,3,13:17:00,2013-10-01,2013-10-10,75.4,70.4,0.0,0.0,0,0,9,6209,Cat,0,domestic shorthair,None,0,1,tabby,brown,white,brown,Tuesday,Thursday
113616,A664261,2013-10-01 11:21:00,Stray,Normal,Intact Female,3 weeks,domestic shorthair,,2013-10-01 13:00:00,2013-09-10,Transfer,Partner,Intact Female,0,0,2013,9,2013,10,1,11:21:00,2013,10,1,13:00:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,21,Kitten,1,domestic shorthair,None,0,1,tortie,Breed Specific,None,tortie,Tuesday,Tuesday

In [12]:
df['is_weekend_intake'] = (df['intake_day_of_week'] >= 5).astype(int)
df.sample(10)

,animal_id,date_intake,intake_type,intake_condition,sex_fixed_intake,age_raw,breed,color,date_outcome,dob,outcome_type,outcome_subtype,sex_fixed_outcome,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,intake_time_of_day,outcome_year,outcome_month,outcome_day_of_week,outcome_time_of_day,date_only_intake,date_only_outcome,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,cat_or_kitten,is_kitten,breed1,breed2,is_cfa_breed,is_domestic_breed,coat_pattern,color1,color2,coat,weekday_intake,weekday_outcome,is_weekend_intake
30088,A760744,2017-10-23 11:56:00,Owner Surrender,Normal,Neutered Male,3 years,persian,black/white,2017-10-28 18:53:00,2014-10-23,Adoption,NaN,Neutered Male,1,1,2014,10,2017,10,0,11:56:00,2017,10,5,18:53:00,2017-10-23,2017-10-28,61.1,49.3,0.69,0.0,1,0,5,1096,Cat,0,persian,None,1,0,NaN,black,white,black,Monday,Saturday,0
33427,A754115,2017-07-15 16:16:00,Owner Surrender,Normal,Intact Female,2 months,domestic shorthair,black/white,2017-08-15 18:02:00,2017-04-30,Adoption,NaN,Spayed Female,0,0,2017,4,2017,7,5,16:16:00,2017,8,1,18:02:00,2017-07-15,2017-08-15,86.5,86.7,0.00,0.0,0,0,31,76,Kitten,1,domestic shorthair,None,0,1,NaN,black,white,black,Saturday,Tuesday,1
61119,A761548,2017-11-06 16:24:00,Stray,Normal,Unknown,1 year,domestic shorthair,black,2017-11-11 13:22:00,2016-11-06,Transfer,Snr,Unknown,0,1,2016,11,2017,11,0,16:24:00,2017,11,5,13:22:00,2017-11-06,2017-11-11,75.7,62.7,0.00,0.0,0,0,5,365,Cat,0,domestic shorthair,None,0,1,NaN,black,None,black,Monday,Saturday,0
28669,A704755,2015-06-08 16:51:00,Stray,Normal,Intact Male,1 month,domestic shorthair,brown,2015-07-18 14:21:00,2015-05-01,Adoption,Foster,Neutered Male,1,0,2015,5,2015,6,0,16:51:00,2015,7,5,14:21:00,2015-06-08,2015-07-18,79.4,84.7,0.00,0.0,0,0,40,38,Kitten,1,domestic shorthair,None,0,1,tabby,brown,None,brown,Monday,Saturday,0
96851,A694205,2014-12-22 14:06:00,Owner Surrender,Normal,Intact Male,1 month,domestic shorthair,blue,2014-12-24 11:40:00,2014-10-22,Adoption,NaN,Neutered Male,1,0,2014,10,2014,12,0,14:06:00,2014,12,2,11:40:00,2014-12-22,2014-12-24,60.0,48.0,0.00,0.0,0,0,2,61,Kitten,1,domestic shorthair,None,0,1,NaN,blue,None,blue,Monday,Wednesday,0
1170,A352713,2017-04-13 16:29:00,Stray,Normal,Spayed Female,13 years,domestic shorthair,silver,2017-04-25 12:25:00,2004-04-16,Transfer,Partner,Spayed Female,0,1,2004,4,2017,4,3,16:29:00,2017,4,1,12:25:00,2017-04-13,2017-04-25,72.4,72.0,0.00,0.0,0,0,12,4745,Cat,0,domestic shorthair,None,0,1,tabby,silver,None,silver,Thursday,Tuesday,0
68345,A708825,2015-08-01 12:06:00,Stray,Normal,Intact Female,1 year,domestic shorthair,,2015-08-02 09:00:00,2014-08-01,Transfer,SCRP,Intact Female,0,0,2014,8,2015,8,5,12:06:00,2015,8,6,09:00:00,2015-08-01,2015-08-02,84.3,82.2,0.00,0.0,0,0,1,365,Cat,0,domestic shorthair,None,0,1,torbie,Breed Specific,None,torbie,Saturday,Sunday,1
102319,A711254,2015-09-04 13:00:00,Stray,Normal,Intact Female,2 months,domestic shorthair,,2015-09-14 17:03:00,2015-06-19,Adoption,NaN,Spayed Female,0,0,2015,6,2015,9,4,13:00:00,2015,9,0,17:03:00,2015-09-04,2015-09-14,83.0,74.3,0.00,0.0,0,0,10,77,Kitten,1,domestic shorthair,None,0,1,tortie,Breed Specific,None,tortie,Friday,Monday,0
113646,A708613,2015-07-29 16:00:00,Owner Surrender,Normal,Spayed Female,6 years,domestic mediumhair,blue,2015-08-06 18:17:00,2009-07-29,Adoption,NaN,Spayed Female,0,1,2009,7,2015,7,2,16:00:00,2015,8,3,18:17:00,2015-07-29,2015-08-06,84.9,86.1,0.00,0.0,0,0,8,2191,Cat,0,domestic mediumhair,None,0,1,NaN,blue,None,blue,Wednesday,Thursday,0
19494,A777960,2018-08-06 12:31:00,Stray,Normal,Intact Female,2 months,domestic shorthair,brown,2018-08-22 12:18:00,2018-05-22,Transfer,Partner,Intact Female,0,0,2018,5,2018,8,0,12:31:00,2018,8,2,12:18:00,2018-08-06,2018-08-22,83.5,89.0,0.01,0.0,0,0,16,76,Kitten,1,domestic shorthair,None,0,1,tabby,brown,None,brown,Monday,Wednesday,0

Below, going to try to have a cumaltive sum of intake for previous week. Here goes nothing:

In [13]:
df['count'] = 1

In [14]:
df = df.set_index(pd.DatetimeIndex(df['date_intake']))

In [15]:
df['intakes_last_week'] = df['count'].rolling('7d').sum()

In [16]:
df.sample(5)

,animal_id,date_intake,intake_type,intake_condition,sex_fixed_intake,age_raw,breed,color,date_outcome,dob,outcome_type,outcome_subtype,sex_fixed_outcome,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,intake_time_of_day,outcome_year,outcome_month,outcome_day_of_week,outcome_time_of_day,date_only_intake,date_only_outcome,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,cat_or_kitten,is_kitten,breed1,breed2,is_cfa_breed,is_domestic_breed,coat_pattern,color1,color2,coat,weekday_intake,weekday_outcome,is_weekend_intake,count,intakes_last_week
date_intake,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2015-08-21 16:13:00,A710333,2015-08-21 16:13:00,Stray,Normal,Intact Female,1 month,domestic shorthair,black/white,2015-09-21 15:54:00,2015-07-06,Transfer,Partner,Intact Female,0,0,2015,7,2015,8,4,16:13:00,2015,9,0,15:54:00,2015-08-21,2015-09-21,76.1,81.5,0.35,0.00,1,0,31,46,Kitten,1,domestic shorthair,None,0,1,NaN,black,white,black,Friday,Monday,0,1,113.0
2016-09-17 12:02:00,A735031,2016-09-17 12:02:00,Stray,Normal,Intact Male,4 weeks,domestic shorthair,blue,2016-09-21 14:16:00,2016-08-17,Transfer,Partner,Intact Male,1,0,2016,8,2016,9,5,12:02:00,2016,9,2,14:16:00,2016-09-17,2016-09-21,82.4,82.6,0.00,0.00,0,0,4,31,Kitten,1,domestic shorthair,None,0,1,tabby,blue,None,blue,Saturday,Wednesday,1,1,104.0
2015-02-16 11:58:00,A697002,2015-02-16 11:58:00,Owner Surrender,Normal,Intact Female,1 year,domestic shorthair,orange /white,2015-03-03 16:43:00,2014-02-16,Transfer,Partner,Spayed Female,0,0,2014,2,2015,2,0,11:58:00,2015,3,1,16:43:00,2015-02-16,2015-03-03,53.6,45.2,0.01,0.01,0,0,15,365,Cat,0,domestic shorthair,None,0,1,tabby,orange,white,orange,Monday,Tuesday,0,1,36.0
2015-05-08 16:09:00,A702062,2015-05-08 16:09:00,Stray,Normal,Intact Male,2 years,domestic shorthair,blue,2015-05-23 13:10:00,2013-05-08,Transfer,Partner,Neutered Male,1,0,2013,5,2015,5,4,16:09:00,2015,5,5,13:10:00,2015-05-08,2015-05-23,76.0,75.5,0.02,0.03,0,0,15,730,Cat,0,domestic shorthair,None,0,1,tabby,blue,None,blue,Friday,Saturday,0,1,159.0
2016-04-08 16:44:00,A723913,2016-04-08 16:44:00,Stray,Normal,Intact Female,4 weeks,domestic shorthair,brown,2016-05-11 10:41:00,2016-03-09,Adoption,Foster,Spayed Female,0,0,2016,3,2016,4,4,16:44:00,2016,5,2,10:41:00,2016-04-08,2016-05-11,63.9,76.3,0.00,0.60,0,1,33,30,Kitten,1,domestic shorthair,None,0,1,tabby,brown,None,brown,Friday,Wednesday,0,1,122.0

In [17]:
df.columns

Index(['animal_id', 'date_intake', 'intake_type', 'intake_condition',
       'sex_fixed_intake', 'age_raw', 'breed', 'color', 'date_outcome', 'dob',
       'outcome_type', 'outcome_subtype', 'sex_fixed_outcome', 'is_male',
       'is_fixed', 'dob_year', 'dob_month', 'intake_year', 'intake_month',
       'intake_day_of_week', 'intake_time_of_day', 'outcome_year',
       'outcome_month', 'outcome_day_of_week', 'outcome_time_of_day',
       'date_only_intake', 'date_only_outcome', 'intake_temp', 'outcome_temp',
       'intake_precip', 'outcome_precip', 'is_rain_intake', 'is_rain_outcome',
       'stay_length', 'real_age_intake_days', 'cat_or_kitten', 'is_kitten',
       'breed1', 'breed2', 'is_cfa_breed', 'is_domestic_breed', 'coat_pattern',
       'color1', 'color2', 'coat', 'weekday_intake', 'weekday_outcome',
       'is_weekend_intake', 'count', 'intakes_last_week'],
      dtype='object')

Below creating specific df's for catboost, as it doesn't take pre-processed dummy variables

First setting month to actual month name

In [18]:
month_dict={1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}

df['intake_month_name'] = df['intake_month'].map(month_dict)
df['outcome_month_name'] = df['outcome_month'].map(month_dict)

Now need to set breed to either "CFA" or "domestic"

In [19]:
cfa_breeds = ['Abyssinian', 'American Bobtail', 'American Curl', 'American Shorthair', 'American Wirehair', 
              'Balinese', 'Bengal', 'Birman', 'Bombay', 'British Shorthair', 'Burmese', 'Burmilla', 
              'Chartreux', 'Colorpoint Shorthair', 'Cornish Rex', 'Devon Rex', 'Egyptian Mau', 'European Burmese', 
              'Exotic', 'Havana Brown', 'Japanese Bobtail', 'Korat', 'LaPerm', 'Maine Coon', 'Manx', 
              'Norwegian Forest Cat', 'Ocicat', 'Oriental', 'Persian', 'Ragamuffin', 'Ragdoll', 'Russian Blue', 
              'Scottish Fold', 'Selkirk Rex', 'Siamese', 'Siberian', 'Singapura', 'Somali', 'Tonkinese', 
              'Turkish Angora', 'Turkish Van']

cfa_breeds = [i.lower() for i in cfa_breeds]
cfa_breeds = '|'.join(cfa_breeds)

In [20]:
df['breed_type'] = np.where((df['breed1'].str.contains(cfa_breeds)) | 
                                (df['breed2'].str.contains(cfa_breeds)), 
                                'CFA Breed', 'Domestic Breed')

And finally creating the df's with this info:

In [43]:
df_X_catboost_all = df.loc[:, ['outcome_type', 
                              'intake_type',
                              'intake_condition',
                              'sex_fixed_intake',
                              'intake_month_name',
                              'weekday_intake', 
                              'outcome_month_name', 
                              'weekday_outcome',
                              'intake_temp',
                              'outcome_temp', 
                              'intake_precip',
                              'outcome_precip',
                              'stay_length',
                              'real_age_intake_days',
                              'cat_or_kitten',
                              'breed_type',
                              'intakes_last_week']]

In [44]:
df_X_catboost_intake_only = df.loc[:, ['outcome_type', 
                              'intake_type',
                              'intake_condition',
                              'sex_fixed_intake',
                              'intake_month_name',
                              'weekday_intake',  
                              'intake_temp', 
                              'intake_precip',
                              'real_age_intake_days',
                              'cat_or_kitten',
                              'breed_type',
                              'intakes_last_week']]

In [45]:
df_X_catboost_outcome_only = df.loc[:, ['outcome_type', 
                              'intake_type',
                              'intake_condition',
                              'sex_fixed_intake', 
                              'outcome_month_name', 
                              'weekday_outcome',
                              'outcome_temp', 
                              'outcome_precip',
                              'stay_length',
                              'real_age_intake_days',
                              'cat_or_kitten',
                              'breed_type']]

In [42]:
df.head()

,animal_id,date_intake,intake_type,intake_condition,sex_fixed_intake,age_raw,breed,color,date_outcome,dob,outcome_type,outcome_subtype,sex_fixed_outcome,is_male,is_fixed,dob_year,dob_month,intake_year,intake_month,intake_day_of_week,intake_time_of_day,outcome_year,outcome_month,outcome_day_of_week,outcome_time_of_day,date_only_intake,date_only_outcome,intake_temp,outcome_temp,intake_precip,outcome_precip,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,cat_or_kitten,is_kitten,breed1,breed2,is_cfa_breed,is_domestic_breed,coat_pattern,color1,color2,coat,weekday_intake,weekday_outcome,is_weekend_intake,count,intakes_last_week,intake_month_name,outcome_month_name,breed_type
date_intake,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2013-10-01 08:33:00,A664235,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:39:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:39:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange,Tuesday,Tuesday,0,1,1.0,October,October,Domestic Breed
2013-10-01 08:33:00,A664237,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange,Tuesday,Tuesday,0,1,2.0,October,October,Domestic Breed
2013-10-01 08:33:00,A664236,2013-10-01 08:33:00,Stray,Normal,Unknown,1 week,domestic shorthair,orange/white,2013-10-01 10:44:00,2013-09-24,Transfer,Partner,Unknown,0,1,2013,9,2013,10,1,08:33:00,2013,10,1,10:44:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,7,Kitten,1,domestic shorthair,None,0,1,NaN,orange,white,orange,Tuesday,Tuesday,0,1,3.0,October,October,Domestic Breed
2013-10-01 10:59:00,A664256,2013-10-01 10:59:00,Owner Surrender,Normal,Neutered Male,17 years,domestic shorthair,brown /white,2013-10-10 13:17:00,1996-10-01,Transfer,Partner,Neutered Male,1,1,1996,10,2013,10,1,10:59:00,2013,10,3,13:17:00,2013-10-01,2013-10-10,75.4,70.4,0.0,0.0,0,0,9,6209,Cat,0,domestic shorthair,None,0,1,tabby,brown,white,brown,Tuesday,Thursday,0,1,4.0,October,October,Domestic Breed
2013-10-01 11:21:00,A664261,2013-10-01 11:21:00,Stray,Normal,Intact Female,3 weeks,domestic shorthair,,2013-10-01 13:00:00,2013-09-10,Transfer,Partner,Intact Female,0,0,2013,9,2013,10,1,11:21:00,2013,10,1,13:00:00,2013-10-01,2013-10-01,75.4,75.4,0.0,0.0,0,0,0,21,Kitten,1,domestic shorthair,None,0,1,tortie,Breed Specific,None,tortie,Tuesday,Tuesday,0,1,5.0,October,October,Domestic Breed

In [24]:
df_dummies = pd.get_dummies(df, columns=['intake_type', 'intake_condition', 'outcome_type', 'intake_year', 'outcome_year', 'weekday_intake', 'weekday_outcome', 'intake_month', 'outcome_month'])

In [25]:
df_dummies_drop_one = pd.get_dummies(df, columns=['intake_type', 'intake_condition', 'outcome_type', 'intake_year', 'outcome_year', 'weekday_intake', 'weekday_outcome', 'intake_month', 'outcome_month'], drop_first=True)

In [26]:
df_X_all_features = df_dummies.loc[:, ['outcome_type_Transfer',
                                       'intakes_last_week',
                                       'is_male', 
                                       'is_fixed', 
                                       'intake_temp', 
                                       'outcome_temp', 
                                       'is_rain_intake', 
                                       'is_rain_outcome', 
                                       'stay_length', 
                                       'real_age_intake_days', 
                                       'is_kitten', 
                                       'is_cfa_breed', 
                                       'is_domestic_breed',
                                       'is_weekend_intake',
                                       'intake_type_Euthanasia Request',
                                       'intake_type_Owner Surrender', 
                                       'intake_type_Stray',
                                       'intake_type_Public Assist',
                                       'intake_condition_Normal', 
                                       'intake_condition_Nursing', 
                                       'intake_condition_Injured', 
                                       'intake_condition_Sick',
                                       'intake_condition_Aged',
                                       'intake_condition_Feral',
                                       'intake_condition_Other',
                                       'intake_condition_Pregnant',
                                       'weekday_intake_Friday',
                                       'weekday_intake_Monday',
                                       'weekday_intake_Saturday',
                                       'weekday_intake_Sunday',
                                       'weekday_intake_Thursday',
                                       'weekday_intake_Tuesday',
                                       'weekday_intake_Wednesday',
                                       'weekday_outcome_Friday',
                                       'weekday_outcome_Monday',
                                       'weekday_outcome_Saturday',
                                       'weekday_outcome_Sunday',
                                       'weekday_outcome_Thursday',
                                       'weekday_outcome_Tuesday',
                                       'weekday_outcome_Wednesday',
                                       'intake_month_1',
                                       'intake_month_2',
                                       'intake_month_3',
                                       'intake_month_4',
                                       'intake_month_5',
                                       'intake_month_6',
                                       'intake_month_7',
                                       'intake_month_8',
                                       'intake_month_9',
                                       'intake_month_10',
                                       'intake_month_11',
                                       'intake_month_12',
                                       'outcome_month_1',
                                       'outcome_month_2',
                                       'outcome_month_3',
                                       'outcome_month_4',
                                       'outcome_month_5',
                                       'outcome_month_6',
                                       'outcome_month_7',
                                       'outcome_month_8',
                                       'outcome_month_9',
                                       'outcome_month_10',
                                       'outcome_month_11',
                                       'outcome_month_12']]

In [27]:
df_X_all_features_drop_one = df_dummies_drop_one.loc[:, ['outcome_type_Transfer', 
                                       'intakes_last_week',
                                       'is_male', 
                                       'is_fixed', 
                                       'intake_temp', 
                                       'outcome_temp', 
                                       'is_rain_intake', 
                                       'is_rain_outcome', 
                                       'stay_length', 
                                       'real_age_intake_days', 
                                       'is_kitten', 
                                       'is_cfa_breed', 
                                       'is_weekend_intake',
                                       'intake_type_Owner Surrender', 
                                       'intake_type_Stray',
                                       'intake_type_Public Assist',
                                       'intake_condition_Normal', 
                                       'intake_condition_Nursing', 
                                       'intake_condition_Injured', 
                                       'intake_condition_Sick',
                                       'intake_condition_Feral',
                                       'intake_condition_Other',
                                       'intake_condition_Pregnant',
                                       'weekday_intake_Monday',
                                       'weekday_intake_Saturday',
                                       'weekday_intake_Sunday',
                                       'weekday_intake_Thursday',
                                       'weekday_intake_Tuesday',
                                       'weekday_intake_Wednesday',
                                       'weekday_outcome_Monday',
                                       'weekday_outcome_Saturday',
                                       'weekday_outcome_Sunday',
                                       'weekday_outcome_Thursday',
                                       'weekday_outcome_Tuesday',
                                       'weekday_outcome_Wednesday',
                                       'intake_month_2',
                                       'intake_month_3',
                                       'intake_month_4',
                                       'intake_month_5',
                                       'intake_month_6',
                                       'intake_month_7',
                                       'intake_month_8',
                                       'intake_month_9',
                                       'intake_month_10',
                                       'intake_month_11',
                                       'intake_month_12',
                                       'outcome_month_2',
                                       'outcome_month_3',
                                       'outcome_month_4',
                                       'outcome_month_5',
                                       'outcome_month_6',
                                       'outcome_month_7',
                                       'outcome_month_8',
                                       'outcome_month_9',
                                       'outcome_month_10',
                                       'outcome_month_11',
                                       'outcome_month_12']]

In [28]:
df_X_intake_only = df_dummies.loc[:, ['outcome_type_Transfer',
                                      'intakes_last_week',
                                       'is_male', 
                                       'is_fixed', 
                                       'intake_temp', 
                                       'is_rain_intake',  
                                       'real_age_intake_days', 
                                       'is_kitten', 
                                       'is_cfa_breed', 
                                       'is_domestic_breed',
                                       'is_weekend_intake',
                                       'intake_type_Euthanasia Request',
                                       'intake_type_Owner Surrender', 
                                       'intake_type_Stray',
                                       'intake_type_Public Assist',
                                       'intake_condition_Normal', 
                                       'intake_condition_Nursing', 
                                       'intake_condition_Injured', 
                                       'intake_condition_Sick',
                                       'intake_condition_Aged',
                                       'intake_condition_Feral',
                                       'intake_condition_Other',
                                       'intake_condition_Pregnant',
                                       'weekday_intake_Friday',
                                       'weekday_intake_Monday',
                                       'weekday_intake_Saturday',
                                       'weekday_intake_Sunday',
                                       'weekday_intake_Thursday',
                                       'weekday_intake_Tuesday',
                                       'weekday_intake_Wednesday',
                                       'intake_month_1',
                                       'intake_month_2',
                                       'intake_month_3',
                                       'intake_month_4',
                                       'intake_month_5',
                                       'intake_month_6',
                                       'intake_month_7',
                                       'intake_month_8',
                                       'intake_month_9',
                                       'intake_month_10',
                                       'intake_month_11',
                                       'intake_month_12',]]

In [29]:
df_X_all_intake_drop_one = df_dummies_drop_one.loc[:, ['outcome_type_Transfer', 
                                       'is_male',
                                       'intakes_last_week',
                                       'is_fixed', 
                                       'intake_temp', 
                                       'is_rain_intake',   
                                       'real_age_intake_days', 
                                       'is_kitten', 
                                       'is_cfa_breed', 
                                       'is_weekend_intake',
                                       'intake_type_Owner Surrender', 
                                       'intake_type_Stray',
                                       'intake_type_Public Assist',
                                       'intake_condition_Normal', 
                                       'intake_condition_Nursing', 
                                       'intake_condition_Injured', 
                                       'intake_condition_Sick',
                                       'intake_condition_Feral',
                                       'intake_condition_Other',
                                       'intake_condition_Pregnant',
                                       'weekday_intake_Monday',
                                       'weekday_intake_Saturday',
                                       'weekday_intake_Sunday',
                                       'weekday_intake_Thursday',
                                       'weekday_intake_Tuesday',
                                       'weekday_intake_Wednesday',
                                       'intake_month_2',
                                       'intake_month_3',
                                       'intake_month_4',
                                       'intake_month_5',
                                       'intake_month_6',
                                       'intake_month_7',
                                       'intake_month_8',
                                       'intake_month_9',
                                       'intake_month_10',
                                       'intake_month_11',
                                       'intake_month_12',]]

In [30]:
df_X_all_features.head()

,outcome_type_Transfer,intakes_last_week,is_male,is_fixed,intake_temp,outcome_temp,is_rain_intake,is_rain_outcome,stay_length,real_age_intake_days,is_kitten,is_cfa_breed,is_domestic_breed,is_weekend_intake,intake_type_Euthanasia Request,intake_type_Owner Surrender,intake_type_Stray,intake_type_Public Assist,intake_condition_Normal,intake_condition_Nursing,intake_condition_Injured,intake_condition_Sick,intake_condition_Aged,intake_condition_Feral,intake_condition_Other,intake_condition_Pregnant,weekday_intake_Friday,weekday_intake_Monday,weekday_intake_Saturday,weekday_intake_Sunday,weekday_intake_Thursday,weekday_intake_Tuesday,weekday_intake_Wednesday,weekday_outcome_Friday,weekday_outcome_Monday,weekday_outcome_Saturday,weekday_outcome_Sunday,weekday_outcome_Thursday,weekday_outcome_Tuesday,weekday_outcome_Wednesday,intake_month_1,intake_month_2,intake_month_3,intake_month_4,intake_month_5,intake_month_6,intake_month_7,intake_month_8,intake_month_9,intake_month_10,intake_month_11,intake_month_12,outcome_month_1,outcome_month_2,outcome_month_3,outcome_month_4,outcome_month_5,outcome_month_6,outcome_month_7,outcome_month_8,outcome_month_9,outcome_month_10,outcome_month_11,outcome_month_12
date_intake,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2013-10-01 08:33:00,1,1.0,0,1,75.4,75.4,0,0,0,7,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2013-10-01 08:33:00,1,2.0,0,1,75.4,75.4,0,0,0,7,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2013-10-01 08:33:00,1,3.0,0,1,75.4,75.4,0,0,0,7,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2013-10-01 10:59:00,1,4.0,1,1,75.4,70.4,0,0,9,6209,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2013-10-01 11:21:00,1,5.0,0,0,75.4,75.4,0,0,0,21,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [31]:
df_X_outcome_only = df_dummies.loc[:, ['outcome_type_Transfer',
                                       'intakes_last_week',
                                       'is_male', 
                                       'is_fixed',  
                                       'outcome_temp',  
                                       'is_rain_outcome', 
                                       'stay_length', 
                                       'real_age_intake_days', 
                                       'is_kitten', 
                                       'is_cfa_breed', 
                                       'is_domestic_breed',
                                       'weekday_outcome_Friday',
                                       'weekday_outcome_Monday',
                                       'weekday_outcome_Saturday',
                                       'weekday_outcome_Sunday',
                                       'weekday_outcome_Thursday',
                                       'weekday_outcome_Tuesday',
                                       'weekday_outcome_Wednesday',
                                       'outcome_month_1',
                                       'outcome_month_2',
                                       'outcome_month_3',
                                       'outcome_month_4',
                                       'outcome_month_5',
                                       'outcome_month_6',
                                       'outcome_month_7',
                                       'outcome_month_8',
                                       'outcome_month_9',
                                       'outcome_month_10',
                                       'outcome_month_11',
                                       'outcome_month_12']]

In [32]:
df_X_outcome_only_drop_one = df_dummies_drop_one.loc[:, ['outcome_type_Transfer', 
                                       'intakes_last_week',
                                       'is_male', 
                                       'is_fixed',  
                                       'outcome_temp', 
                                       'is_rain_outcome', 
                                       'stay_length', 
                                       'real_age_intake_days', 
                                       'is_kitten', 
                                       'is_cfa_breed', 
                                       'weekday_outcome_Monday',
                                       'weekday_outcome_Saturday',
                                       'weekday_outcome_Sunday',
                                       'weekday_outcome_Thursday',
                                       'weekday_outcome_Tuesday',
                                       'weekday_outcome_Wednesday',
                                       'outcome_month_2',
                                       'outcome_month_3',
                                       'outcome_month_4',
                                       'outcome_month_5',
                                       'outcome_month_6',
                                       'outcome_month_7',
                                       'outcome_month_8',
                                       'outcome_month_9',
                                       'outcome_month_10',
                                       'outcome_month_11',
                                       'outcome_month_12']]

In [33]:
#pickling all features with no dropped dummies

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_all.pickle', 'wb') as to_write:
    pickle.dump(df_X_all_features, to_write)

In [34]:
#pickling all features with dropped first dummy for logistic regression

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_all_drop_one.pickle', 'wb') as to_write:
    pickle.dump(df_X_all_features_drop_one, to_write)

In [35]:
#pickling all INTAKE ONLY features with no dropped dummies. For predictions only on intake data

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_intake_only.pickle', 'wb') as to_write:
    pickle.dump(df_X_intake_only, to_write)

In [36]:
#pickling all INTAKE ONLY features with one dropped dummies. For predictions only on intake data

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_intake_only_drop_one.pickle', 'wb') as to_write:
    pickle.dump(df_X_all_intake_drop_one, to_write)

In [37]:
#pickling all OUTCOME ONLY features with no dropped dummies. For predictions only on outcome data

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_outcome_only.pickle', 'wb') as to_write:
    pickle.dump(df_X_outcome_only, to_write)

In [38]:
#pickling all OUTCOME ONLY features with one dropped dummies. For predictions only on outcome data

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_outcome_only_drop_one.pickle', 'wb') as to_write:
    pickle.dump(df_X_outcome_only_drop_one, to_write)

In [46]:
#pickling all features with no dummies for catboost

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_catboost.pickle', 'wb') as to_write:
    pickle.dump(df_X_catboost_all, to_write)

In [47]:
#pickling intake features with no dummies for catboost

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_catboost_intake.pickle', 'wb') as to_write:
    pickle.dump(df_X_catboost_intake_only, to_write)

In [48]:
#pickling outcome features with no dummies for catboost

with open('/Users/robertpagano/src/metis_project_mcnulty/data/final_for_modeling/final_features_catboost_outcome.pickle', 'wb') as to_write:
    pickle.dump(df_X_catboost_outcome_only, to_write)

In [50]:
#Sending df to csv for EDA in Tablaeu
df.to_csv('/Users/robertpagano/src/metis_project_mcnulty/data/interim_data/df.csv')